# before committing check this file here: https://lint.travis-ci.org/
language: python

git:
  quiet: true

matrix:
    include:
    # Linux tests for various python versions
        - python: 3.6
        - python: 3.7
        - python: 3.8

sudo: false

# run tests
script:
  - flake8 .
